Add context initiation with channel bindings token
estokes/cross-krb5 pull request #5
Opened 2022-03-24 11:06 UTC by inejge

This PR depends on estokes/libgssapi#9, and uses it to add a method for initiating a context with optional channel binding data.

Since `initiate()` is a one-stop method, adding a data parameter must be done either by changing its signature, thus breaking compatibility, or by adding a separate method. I chose the latter and wrote `initiate_with_cbt()`.

The patch is Unix-only because I don't have access to a Windows development environment, nor much experience with developing on Windows. The patch is self-contained and usable as-is, but I understand that you may find it unacceptable if your goal is to keep cross-platform parity at all times.

2022-03-25 21:23 UTC, inejge commented
I managed to find a Vagrantfile for a time-limited Windows installation with the complete Rust environment, so I gave it a spin and added the Windows code. Hooray for Vagrant, and the changes weren't too bad. I also changed the API to follow the latest `libgssapi` changes, so this crate will also need a version bump.

2022-03-27 16:29 UTC, estokes requested changes

2022-03-27 16:29 UTC, estokes commented on src/windows.rs
> +            in_buf = SecBuffer {
Is it not possible to pass both a token and a channel binding? I'm not happy about overwriting the token buffer here, if it isn't possible to have both token and a channel binding then the input type should change to make that state impossible, and then match to build the correct buffer type.

2022-03-27 16:31 UTC, estokes commented on src/windows.rs
> +            in_buf = SecBuffer {
And f that state is impossible for gssapi as well then we should also change if there. I'm sorry I've never used channel bindings before, so I'm not entirely up to speed on them yet.

2022-03-28 10:08 UTC, inejge commented on src/windows.rs
> +            in_buf = SecBuffer {
> Is it not possible to pass both a token and a channel binding?

In the reams of RFCs that I've read nothing explicitly prohibits it on the client side, but it makes no sense to have both, assuming that the initial token is empty: you'd want to pass the channel bindings as soon as possible and terminate the authentication exchange if they don't match on both sides.

> I'm not happy about overwriting the token buffer here, if it isn't possible to have both token and a channel binding then the input type should change to make that state impossible

The elements are moved out of and there shouldn't be any memory leaks or dangling  pointers, but you're right, having it in type-safe wrappers makes for clearer code. I've prepared a refactoring which introduces an internal enum for classifying the possible input data states.

> And if that state is impossible for gssapi as well then we should also change if there.

It doesn't say it's impossible anywhere that I've seen, so I think it should stay as is, although I doubt that anyone will come up with an authentication flow which would combine a server token with channel bindings.

2022-03-28 18:11 UTC, merged